name: GhettoEnchants
main: me.vemacs.ghettoenchants.EnchantsPlugin
version: ${project.version}
commands:
   giveenchanteditem:
        description: Gives a player an item with the applied enchants
        aliases: [gei]
        permission: ghettoenchants.admin
        usage: /giveenchanteditem [player] [material] [enchant1:2,enchant2:3]
permissions:
    ghettoenchants.admin:
        default: op
        description: Admin permissions for this plugin.